
- name: Add docker apt key
  shell: curl -sSL https://get.docker.com/ | sh


- name: Add ppa for PHP
  apt_repository: repo='ppa:ondrej/php5'

- name: Install required packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-gd
    - php5-intl
    - php5-imagick
    - php5-imap
    - php5-mcrypt
    - php5-memcache
    - php5-ps
    - php5-pspell
    - php5-recode
    - php5-sqlite
    - php5-tidy
    - php5-xmlrpc
    - php5-xsl
    - php5-xcache
    - php-pear
    - gettext-base
    - zip


- name: Install NodeJS ppa
  shell: curl -sL https://deb.nodesource.com/setup | bash -

- name: Install NodeJS
  apt: name=nodejs state=latest update_cache=yes

- name: Install latest npm version
  shell: npm install -g npm@latest-2

- name: Install gulp
  shell: npm install -g gulp

- name: Install bower
  shell: npm install -g bower

- name: Download rancher-compose
  unarchive: src="https://github.com/rancher/rancher-compose/releases/download/v0.8.1/rancher-compose-linux-amd64-v0.8.1.tar.gz" dest=/tmp/ copy=no

- name: Move binary and add permissions
  shell: mv /tmp/rancher-compose-v0.8.1/rancher-compose /usr/local/bin/rancher-compose; chmod +x /usr/local/bin/rancher-compose
